

services: 
  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
  app:
    image: node:18
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    ports: 
      - "3000:3000"
    command: "npm start"
    environment:
      - MONGO_URI=mongodb://admin:password@db:27017/core-academy?authSource=admin
      - JWT_SECRET=testing_jwt_secret
  db-interface:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password